src/Entity/Budget.php
<?php

namespace App\Entity;

use App\Repository\BudgetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BudgetRepository::class)]
class Budget
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Amount = null;

    #[ORM\OneToMany(mappedBy: 'budget', targetEntity: Position::class)]
    private Collection $position;

    public function __construct()
    {
        $this->position = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?int
    {
        return $this->Amount;
    }

    public function setAmount(int $Amount): self
    {
        $this->Amount = $Amount;

        return $this;
    }

    /**
     * @return Collection<int, Position>
     */
    public function getPosition(): Collection
    {
        return $this->position;
    }

    public function addPosition(Position $position): self
    {
        if (!$this->position->contains($position)) {
            $this->position->add($position);
            $position->setBudget($this);
        }

        return $this;
    }

    public function removePosition(Position $position): self
    {
        if ($this->position->removeElement($position)) {
            // set the owning side to null (unless already changed)
            if ($position->getBudget() === $this) {
                $position->setBudget(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    #[ORM\OneToOne(mappedBy: 'users', cascade: ['persist', 'remove'])]
    private ?Position $position = null;

    #[ORM\ManyToMany(targetEntity: Command::class, mappedBy: 'users')]
    private Collection $commands;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?LeftBudget $leftBudget = null;

    public function __construct()
    {
        $this->commands = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->FirstName;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getPosition(): ?Position
    {
        return $this->position;
    }

    public function setPosition(Position $position): self
    {
        // set the owning side of the relation if necessary
        if ($position->getUsers() !== $this) {
            $position->setUsers($this);
        }

        $this->position = $position;

        return $this;
    }

    /**
     * @return Collection<int, Command>
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Command $command): self
    {
        if (!$this->commands->contains($command)) {
            $this->commands->add($command);
            $command->addUser($this);
        }

        return $this;
    }

    public function removeCommand(Command $command): self
    {
        if ($this->commands->removeElement($command)) {
            $command->removeUser($this);
        }

        return $this;
    }

    public function getLeftBudget(): ?LeftBudget
    {
        return $this->leftBudget;
    }

    public function setLeftBudget(?LeftBudget $leftBudget): self
    {
        $this->leftBudget = $leftBudget;

        return $this;
    }
}

src/Controller/UserCommandController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Command;
use App\Entity\LeftBudget;
use App\Entity\Quantity;
use App\Entity\User;
use App\Repository\ArticleRepository;
use App\Repository\CommandRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;



class UserCommandController extends AbstractController
{
    #[Route('/user/command', name: 'app_user_command')]
    public function index(SessionInterface $session, ArticleRepository $ArtRepo): Response
    {   
        
        $command = $session->get("command",[]);
        $datacommand=[];
        $total=0;
        $lbudget= 0;
        //$user->;
        //$budget= $user->getLeftBudget();
        foreach($command as $id => $quantity){
            $article = $ArtRepo->find($id);
            $datacommand[] = [
                "article"=>$article,
                "quantity"=>$quantity
            ];
            $total += $article->getPrice()*$quantity;
            
            
        }


        return $this->render('user_command/index.html.twig', compact("datacommand","total","lbudget")
        );
    }

    #[Route('/user/command/add/{id}', name: 'app_user_command_add')]
    public function addCommand(Article $article, SessionInterface $session): Response
    {   
        $command= $session->get("command",[]);
        $id = $article ->getId();

        if(!empty($command[$id])){
            $command[$id]++;
        }
        else{
            $command[$id] = 1;
        }

        $session->set("command",$command);
        return $this->redirectToRoute('app_user_command');        
    }

    #[Route('/user/command/remove/{id}', name: 'app_user_command_remove')]
    public function RemoveCommand(Article $article, SessionInterface $session): Response
    {   
        $command= $session->get("command",[]);
        $id = $article ->getId();

        if(!empty($command[$id])){
            if($command[$id] > 1 ){
                $command[$id]--;
            }else{
                unset($command[$id]);
            }
            
        }
      

        $session->set("command",$command);
        return $this->redirectToRoute('app_user_command');

       
    }

    #[Route('/user/command/delete/{id}', name: 'app_user_command_delete')]
    public function DeleteCommand(Article $article, SessionInterface $session): Response
    {   
        $command= $session->get("command",[]);
        $id = $article ->getId();

        if(!empty($command[$id])){
            
                unset($command[$id]);
            
        }
      

        $session->set("command",$command);
        return $this->redirectToRoute('app_user_command');

       
    }

    #[Route('/user/command/viewcommand', name: 'app_user_view_command')]
    public function UserViewCommand(ArticleRepository $ArtRepo,Request $request,EntityManagerInterface $entityManager,CommandRepository $comRep,SessionInterface $session): Response
    {   
       
       $total=0.0;
       $user = $this->getUser();
       $commands= new Command();
       $command = $session->get("command",[]);
       $datacommand=[];
       foreach($command as $id => $quantity){
            $article = $ArtRepo->find($id);
            $datacommand[] = [
            "articles"=>$article,
            "quantity"=>$quantity
                         ];
            $cart[$article->getId()]=['quantity'=>$quantity];
            $commands->addArticle($article);
            $commands->setQuantity($quantity);
            $commands->addUser($user);
            $total += $article->getPrice()*$quantity;
            $commands->setAmount($total); 
            $commands->setDate(new \DateTime());
            $entityManager->persist($commands);
            $entityManager->flush(); 
        }
    
  
     return $this->redirectToRoute('app_user_home_command', compact("commands"));
           
    }


    #[Route('/user/command/homecommand', name: 'app_user_home_command')]
    public function homeCommand(CommandRepository $ComRep): Response
    {
        $user = $this->getUser();
        return $this->render('user_command/commandview.html.twig', ['commands' => $ComRep->findAll(),'user'=>$user]);
    }

}

templates/user_command/command.html.twig
{% extends 'base.html.twig' %}

{% block title %} PAD | Commands{% endblock %}

{% block stylesheets %}
<style>
    a {
        font-size:14px;
        font-weight:700;
      }
    .superNav {
        font-size:13px;
      }
    .form-control {
        outline:none !important;
        box-shadow: none !important;
      }
    @media screen and (max-width:540px){
        .centerOnMobile {
          text-align:center;
        }
      }
      
</style>
{% endblock %}

{% block body %}

  <nav class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm">
    <div class="container">
        <div class="nav-item">
            <img src="{{ asset('images/logoPAD.png') }}"
        style="width:50px;" alt="logo">
        </div> 
      <a class="navbar-brand" href="#"><i class="fa-solid fa-shop me-2"></i> <strong>PAD STORE</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
   
      <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block">
        <div class="input-group">
          <span class="border-primary input-group-text bg-primary text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
          <input type="text" class="form-control border-primary" style="color:#7a7a7a">
          <button class="btn btn-primary text-white">Search</button>
        </div>
      </div>
      <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <div class="ms-auto d-none d-lg-block">
          <div class="input-group">
            <span class="border-primary input-group-text bg-primary text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control border-primary" style="color:#7a7a7a">
            <button class="btn btn-primary text-white">Search</button>
          </div>
        </div>
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" aria-current="page" href="{{ path("app_user_article")}}">Articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{{ path("app_user_command")}}">Commands</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase active" href="{{ path("app_user_home_command")}}">View Commands</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{{path('app_logout')}}"><i class="fa-solid fa-circle-user me-1"></i> Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav><br>

  <table class="table table-striped caption-top">
    <caption><h2>View commands </h2></caption>
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Articles</th>
        <th scope="col">Quantity</th>
        <th scope="col">User Name</th>
        <th scope="col">Amount</th>
        <th scope="col">Date</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
   <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
   </tr>    
    </tbody>
  </table>
  
  {{ dump(datacommand) }}
{% endblock %}

templates/user_command/commandview.html.twig
{% extends 'base.html.twig' %}

{% block title %} PAD | Commands{% endblock %}

{% block stylesheets %}
<style>
    a {
        font-size:14px;
        font-weight:700;
      }
    .superNav {
        font-size:13px;
      }
    .form-control {
        outline:none !important;
        box-shadow: none !important;
      }
    @media screen and (max-width:540px){
        .centerOnMobile {
          text-align:center;
        }
      }
      
</style>
{% endblock %}

{% block body %}

  <nav class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm">
    <div class="container">
        <div class="nav-item">
            <img src="{{ asset('images/logoPAD.png') }}"
        style="width:50px;" alt="logo">
        </div> 
      <a class="navbar-brand" href="#"><i class="fa-solid fa-shop me-2"></i> <strong>PAD STORE</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
   
      <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block">
        <div class="input-group">
          <span class="border-primary input-group-text bg-primary text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
          <input type="text" class="form-control border-primary" style="color:#7a7a7a">
          <a href="#" class="btn btn-primary text-white">Search</a>
        </div>
      </div>
      <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <div class="ms-auto d-none d-lg-block">
          <div class="input-group">
            <span class="border-primary input-group-text bg-primary text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control border-primary" style="color:#7a7a7a">
            <a href="#" class="btn btn-primary text-white">Search</a>
          </div>
        </div>
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" aria-current="page" href="{{ path("app_user_article")}}">Articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{{ path("app_user_command")}}">Commands</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase active" href="{{ path("app_user_home_command")}}">View Commands</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{{path('app_logout')}}"><i class="fa-solid fa-circle-user me-1"></i> Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav><br>

  <table class="table table-striped caption-top">
    <caption><h2>View commands </h2></caption>
    
      {% for command in commands %}
          {% if user.FirstName == app.user.userIdentifier %}
      <thead>
        <tr>
          <caption><th colspan="6"><h3> Command ID: {{ command.id }}</h3></th></caption>
        </tr>
      <tr>
        <th scope="col"></th>
        <th scope="col">Articles</th>
        <th scope="col">Quantity</th>
        <th scope="col">Amount</th>
        <th scope="col">Date</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td></td>
            <td>
              {% for article in command.articles %}
              {{ article.Name }}
              <br>
              {% endfor %}
            </td>
            <td>{{command.quantity}}</td>
            <td>{{ command.amount }} FCFA</td>
            <td>{{ command.Date|date("m/d/Y") }}</td>
            <td></td>
          </tr>

          {% endif %}
      {% endfor %}
    </tbody>
  {{ dump(commands) }}
  </table>
  
 
{% endblock %}

templates/user_command/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} PAD | Articles{% endblock %}

{% block stylesheets %}
<style>
    a {
        font-size:14px;
        font-weight:700;
      }
    .superNav {
        font-size:13px;
      }
    .form-control {
        outline:none !important;
        box-shadow: none !important;
      }
    @media screen and (max-width:540px){
        .centerOnMobile {
          text-align:center;
        }
      }
      
</style>
{% endblock %}

{% block body %}

  <nav class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm">
    <div class="container">
        <div class="nav-item">
            <img src="{{ asset('images/logoPAD.png') }}"
        style="width:50px;" alt="logo">
        </div> 
      <a class="navbar-brand" href="#"><i class="fa-solid fa-shop me-2"></i> <strong>PAD STORE</strong></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
   
      <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block">
        <div class="input-group">
          <span class="border-primary input-group-text bg-primary text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
          <input type="text" class="form-control border-primary" style="color:#7a7a7a">
          <a href="#" class="btn btn-primary text-white">Search</a>
        </div>
      </div>
      <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <div class="ms-auto d-none d-lg-block">
          <div class="input-group">
            <span class="border-primary input-group-text bg-primary text-white"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control border-primary" style="color:#7a7a7a">
            <a href="#" class="btn btn-primary text-white">Search</a>
          </div>
        </div>
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" aria-current="page" href="{{ path("app_user_article")}}">Articles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase active" href="{{ path("app_user_command")}}">Commands</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{{ path("app_user_home_command")}}">View Commands</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2 text-uppercase" href="{{path('app_logout')}}"><i class="fa-solid fa-circle-user me-1"></i> Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav><br>
  <div><h2>Budget left : {{ 250000 - total  }}

  </h2></div>
  <a href="{{path('app_pdf_generator')}}" class="btn btn-primary position-relative" style="float: right ; margin-right:50px; margin-top:10px;">
    Print Command
  </a>
  <a href="{{ path("app_user_view_command")}}" class="btn btn-primary position-relative" style="float: right ; margin-right:50px; margin-top:10px;">
    Complete command 
  </a>
  <table class="table table-striped caption-top">
    <caption><h2>Command </h2></caption>
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Article Name</th>
        <th scope="col">Category</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     
        {% for element in datacommand %}
        <tr>
            <td>{{ element.article.id}}</td>
            <td>{{ element.article.Name}}</td>
            <td>{{ element.article.category.Name}}</td>
            <td>{{ element.quantity}}</td>
            <td>{{ element.article.Price}} FCFA</td>
            <td>{{ element.quantity * element.article.Price }} FCFA</td>
            <td> <a href="{{path("app_user_command_add", {id: element.article.id})}}" class="btn btn-succes"> <h3><i class="bi bi-plus-circle-fill" style="color: blue;"></i></h3></a>
                <a href="{{path("app_user_command_remove", {id: element.article.id})}}" class="btn btn-warnin"><h3><i class="bi bi-dash-circle-fill" style="color: grey;"></i></h3></a>
                <a href="{{path("app_user_command_delete", {id: element.article.id})}}" class="btn btn-dange"><h3><i class="bi bi-x-circle-fill" style=" color:red;"></i> </h3></a>
            </td>
            <td></td>
        </tr>
        {% else %}
        <tr>
            <td colspan="6" class="text-center">No commands</td>
        </tr>
        {% endfor %}
          
    </tbody>
    <tfoot><br>
        <tr>
            <td colspan="3" class="text-center"><h4><b>Total</b> </h4></td>
            <td colspan="text-end"><h4><b>{{ total }} FCFA</b></h4></td>
            
        </tr>
    </tfoot>
    
  </table>
{% endblock %}